services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8201:8200"
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DEV_LISTEN_ADDRESS=${VAULT_DEV_LISTEN_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID} -dev-listen-address=${VAULT_DEV_LISTEN_ADDRESS}
